version: 1.0
app:
  maven:
    groupId: "libertyDefaultApplication"
    artifactId: "libertyDefaultApplication"
    version: "1.0.3"
    type: ear
  endpoints: public
  instances:
    min: 1
    max: 5
